apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      serviceAccount: capture-system-sa
      containers:
      - args:
        - --stream_cap_svr=capture-stream-server-svc.capture-system.svc.cluster.local:9890
        command:
        - /capture-agent
        env:
        - name: CNA_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CNA_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: CNA_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CNA_APP_LABEL
          value: echoserver
        image: nmalhotra/capture-agent:latest
        imagePullPolicy: Always
        name: capture-agent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: echoserver