apiVersion: v1
data:
kind: Secret
metadata:
  name: {{ .Values.webhook.validating.name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Create a placeholder secret so that the capture-manager does not fail to start 
  # due to mount failures. The actual secret with the certificates will be created
  # by the operator framework, replacing this secret and its contents.
  cert: cGxhY2Vob2xkZXIK