apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace:  &deploymentNamespace {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    appTitle: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      appTitle: {{ .Values.name }}
  template:
    metadata:
     labels:
      app: {{ .Values.name }}
      appTitle: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: &containerNameWorker capture-stream-server
        image: &containerImageWorker "{{ .Values.docker.image.name }}:{{ .Values.docker.image.tag }}"
        imagePullPolicy: Always
        command:
        - /entry-point
        args:
        - --port={{ .Values.grpc.port }}
        - --capture_path={{ .Values.capturePath }}/captures
        securityContext:                                                                                
          capabilities:                                                                                 
            add:                                                                                        
            - NET_ADMIN                                                                                 
            - NET_RAW                                                                                   
            drop:                                                                                       
            - ALL
          privileged: false
          runAsNonRoot: false                                                                                    
          runAsUser: 0                                                                                    
        ports:
         - name:          server-grpc
           containerPort: {{ .Values.grpc.port }}
        resources:
          requests:
            cpu: {{ .Values.hpa.workerCpuRequests }}
        env:
          - name: CNA_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CNA_NODE_IPADDR
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: CNA_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: CNA_CONTAINER_NAME
            value: *containerNameWorker
          - name: CNA_CONTAINER_IMAGE
            value: *containerImageWorker
          - name: CNA_NAMESPACE
            value: *deploymentNamespace
          - name: CNA_ISTIO_PROXY
            value: "true"
          - name: CNA_APP_TARGET_PORT
            value: "9890"
          - name: CNA_APP_TARGET_PORT_NAME
            value: "server-grpc"
          - name: CNA_POD_SERVICE
            value: "{{ .Values.name }}"
          - name: CNA_POD_SERVICE_IPPORT
            value: "9890"
          - name: CNA_FEDERATION_NAME
            value: *deploymentNamespace
          - name: TRACING_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
