apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
  - name: server-grpc
    port: 9890
    targetPort: 9890
  selector:
    app: {{ .Values.name }}
